### ISSUE TITLE
May I translate your post in Korean?

### ISSUE THREAD

**Issue by JunHyeokHa** [leerob/next-prisma#2]
Hi, I am a student majoring in computer science.

I've been interested in JAMstack recently.

I read your [post](https://leerob.io/blog/next-prisma), this post is very cool!!!!

I want to translate your post and post it on my blog for sharing tech.

Of course I will write your blog link on the top.

If you are ok, I'll translate it!!

Thanks :)

**Comment by leerob** [comment]
Hey! Yeah, absolutely. Thank you for translating, I appreciate it 🙏

**Comment by JunHyeokHa** [comment]
I finished translate :)

Here is my [Link](https://velog.io/@sirl/Next.js-9.3%EA%B3%BC-Prisma%EB%A1%9C-%EC%A0%95%EC%A0%81-%EC%9B%B9%ED%8E%98%EC%9D%B4%EC%A7%80-%EB%A7%8C%EB%93%A4%EA%B8%B0)

Thank you for your posting again 👍

**Comment by leerob** [comment]
Thank you so much!
