### ISSUE TITLE
Would this deploy to Vercel?

### ISSUE THREAD

**Issue by jnthnk** [leerob/next-prisma#5]
**Hi Lee! Excelent example.**

I'm just wondering if prisma would work if I deploy it to a free account of vercel.

In affirmative case, it should only work with SQLite?

Thanks

**Comment by leerob** [comment]
It will deploy to Vercel with a free account and can work with any SQL-based database. It's important to note that it's currently only reading from the database at _build_ time, not at run time. 

If you want to make updates to the database, then you'll want to host your database somewhere else, like Heroku, Digital Ocean, or AWS.

**Comment by jnthnk** [comment]
I found this example of prisma itself: https://github.com/prisma/prisma-examples/tree/master/typescript/rest-nextjs

It had support for POST and PUT endpoints using a file-based database inside next.

I just wanna use next.js without havind to build other platform for managing small databases.

Maybe this is a different methodology? Or is impossible?

**Comment by leerob** [comment]
Vercel doesn't host databases. For a similar workflow deploying your Next app and database together, you could check out Render. 

https://github.com/kunalgorithm/fullstack-twitter

**Comment by jnthnk** [comment]
So, I should misunderstood the example provided by primsa.

Thanks for your time. Keep the good work. I really enjoy the next course.

**Comment by leerob** [comment]
No problem! Happy to help 😄
